FROM anthesevenants/roodgroen:base
# We start from the R Studio base

# Let's set the working directory correctly (also for the R environment itself)
RUN echo "setwd(\"/home/rstudio/ElasticRoodGroen/\")" > ~/../home/rstudio/.Rprofile
RUN mkdir -p "/home/rstudio/.local/share/rstudio/projects_settings/"
RUN mkdir -p "/root/.local/share/rstudio/projects_settings/"
RUN chmod -R 777 "/home/rstudio/.local/"
RUN chmod -R 777 "/root/.local/"
RUN echo "/home/rstudio/ElasticRoodGroen/ElasticRoodGroen.Rproj" > "/home/rstudio/.local/share/rstudio/projects_settings/last-project-path"
RUN echo "/home/rstudio/ElasticRoodGroen/ElasticRoodGroen.Rproj" > "/root/.local/share/rstudio/projects_settings/last-project-path"