FROM rocker/rstudio:4

RUN R -q -e 'install.packages(c("magrittr", "stringr", "data.table", "glmnet", "dbscan", "Rtsne", "umap", "vegan", "doMC", "stringdist", "DescTools", "nonnest2", "MuMIn", "dplyr", "cowplot", "ggnewscale", "ggplot2"))'